services:
  db-pg:
    image: pgvector/pgvector:pg18
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pg}
      POSTGRES_DB: ${POSTGRES_DB:-cs419_db}
    
  # db-qdrant:
  #   image: qdrant/qdrant:dev
  #   ports:
  #     - "${QDRANT_PORT:-6333}:6333"
  #   volumes:
  #     - ./.storage/qdrant_data:/qdrant/storage

volumes:
  pg_data: