services:
  etcd:
    container_name: milvus-etcd
    env_file: .env 
    image: quay.io/coreos/etcd:v3.5.25
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: 1000
      ETCD_QUOTA_BACKEND_BYTES: 4294967296
      ETCD_SNAPSHOT_COUNT: 50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/.milvus/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:${ETCD_PORT:-2379} -listen-client-urls http://0.0.0.0:${ETCD_PORT:-2379} --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    container_name: milvus-minio
    env_file: .env 
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_CONSOLE_PORT:-9001}:${MINIO_CONSOLE_PORT:-9001}"
      - "${MINIO_PORT:-9000}:${MINIO_PORT:-9000}"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/.milvus/minio:/minio_data
    command: minio server /minio_data --console-address ":${MINIO_CONSOLE_PORT:-9001}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT:-9000}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  standalone:
    container_name: milvus-standalone
    env_file: .env
    image: milvusdb/milvus:v2.6.11
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:${ETCD_PORT:-2379}
      MINIO_ADDRESS: minio:${MINIO_PORT:-9000}
      MQ_TYPE: woodpecker
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/.milvus/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MILVUS_HEALTH_PORT:-9091}/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "${MILVUS_PORT:-19530}:${MILVUS_PORT:-19530}"
      - "${MILVUS_HEALTH_PORT:-9091}:${MILVUS_HEALTH_PORT:-9091}"
    depends_on:
      - "etcd"
      - "minio"

networks:
  default:
    name: milvus
